#!/usr/bin/env bash
# Nginx configuration | custom 404 page
sudo apt-get update
sudo apt-get install nginx -y
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sed -i "/server_name _;/a rewrite ^/redirect_me/(.*)$ https://ddg.gg permanent;" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee -a /usr/share/nginx/html/404.html
sed -i "/server_name _;/a error_page 404 /404.html;location = /404.html { root /usr/share/nginx/html; internal; }" /etc/nginx/sites-available/default
sudo service nginx restart
