#!/usr/bin/env bash
# Displays to infinity and beyond indefinitely
# I am invincible!!! when receiving a SIGTERM signal
function ctrlc()
{
    echo "I am invincible!!!"
}
trap ctrlc SIGTERM
while true
do
    echo " To infinity and beyond "
    sleep 2
done
